const ActionTypes = {
    FETCH_AIRPORT_LIST_LOADING: "FETCH_AIRPORT_LIST_LOADING",
    FETCH_AIRPORT_LIST_SUCCESS: "FETCH_AIRPORT_LIST_SUCCESS",
    FETCH_AIRPORT_LIST_ERROR: "FETCH_AIRPORT_LIST_ERROR",
    FETCH_AIRPORT_APP_LOADING: "FETCH_AIRPORT_APP_LOADING",
    FETCH_AIRPORT_APP_LOADED: "FETCH_AIRPORT_APP_LOADED"
}

export default ActionTypes;